export const INDIAN_STATES = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];

export const BUSINESS_NATURES = [
  'Retail Trade',
  'Wholesale / Distribution',
  'E-Commerce Seller (Amazon, Flipkart, Meesho)',
  'Software & Information Technology',
  'Manufacturing',
  'Professional Services / Freelancer',
  'Works Contract / Construction',
  'Hospitality & Restaurants',
  'Logistics & Transport',
  'Healthcare / Clinic',
  'Export / Import (IEC)',
  'Other Commercial Services',
];

export const GST_DEFAULT_PLAN = {
  serviceName: 'GST Registration (GST Registration + Monthly Filing)',
  subtotal: 1499,
  gstRate: 18,
  gstAmount: 270,
  totalAmount: 1769,
  billingCycle: 'Monthly',
};
