import React, { useState } from 'react';
import { ChevronDown, ChevronUp, HelpCircle } from 'lucide-react';
import Breadcrumbs from '../components/common/Breadcrumbs.jsx';

export default function FaqPage() {
  const [openIdx, setOpenIdx] = useState(0);

  const categories = [
    {
      category: 'GST Registration Basics',
      faqs: [
        {
          q: 'Who mandatorily requires GST registration in India?',
          a: 'Under the Central Goods and Services Tax (CGST) Act, registration is mandatory for any business supplying goods with an aggregate annual turnover exceeding ₹40 Lakhs (₹20 Lakhs in northeastern/hilly states), or ₹20 Lakhs for services (₹10 Lakhs in special states). Furthermore, e-commerce sellers, interstate traders, and exporters require compulsory registration irrespective of turnover.',
        },
        {
          q: 'Can I operate from home without a separate commercial office?',
          a: 'Yes. The GST department permits using residential premises as your principal place of business. You need to provide a recent electricity bill of the residential property, a No Objection Certificate (NOC) signed by the property owner, and a simple consent or rent agreement.',
        },
      ],
    },
    {
      category: 'Documents & Verification',
      faqs: [
        {
          q: 'Why is an electricity bill or utility bill mandatory?',
          a: 'GST Rule 8 requires documentary evidence of physical possession of the business premises. An electricity bill less than 2 months old or a municipal property tax receipt is the standard accepted verification proof by state and central GST officers.',
        },
        {
          q: 'What if there is a name discrepancy between my PAN and Aadhaar?',
          a: 'Minor spelling variations between PAN and Aadhaar are a common reason for automatic government rejection. BharatFiling’s AI flags this mismatch during your pre-check, allowing our Chartered Accountant to attach a supporting affidavit and PAN verification slip during Form REG-01 filing.',
        },
      ],
    },
    {
      category: 'Process, ARN & Delivery',
      faqs: [
        {
          q: 'What is an Application Reference Number (ARN)?',
          a: 'The ARN is a unique 15-character alphanumeric number generated by the GST Common Portal once Form REG-01 is successfully filed. It confirms that your application has entered the statutory verification queue of the jurisdictional tax officer.',
        },
        {
          q: 'How long does approval take?',
          a: 'Standard GST registration typically takes between 3 to 7 working days once submitted on the portal, assuming Aadhaar biometric authentication is completed. If the tax officer issues a query (Notice REG-03), our CA files the response within 24 hours to secure swift approval.',
        },
      ],
    },
  ];

  return (
    <div className="min-h-screen bg-slate-50 font-sans">
      <Breadcrumbs items={[{ label: 'Knowledge Base & FAQs' }]} />
      <div className="py-14 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto space-y-12">
        <div className="text-center space-y-3">
          <span className="text-xs font-bold uppercase tracking-wider text-emerald-700 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-200">
            Knowledge Base
          </span>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900">
            GST & Compliance Frequently Asked Questions
          </h1>
          <p className="text-sm text-slate-600">
            Everything you need to know about GST registration, documentation, and the filing lifecycle.
          </p>
        </div>

        <div className="space-y-8">
          {categories.map((cat, cIdx) => (
            <div key={cIdx} className="space-y-3">
              <h2 className="text-base font-black text-slate-900 border-b border-slate-200 pb-2">
                {cat.category}
              </h2>
              <div className="space-y-2">
                {cat.faqs.map((faq, fIdx) => {
                  const globalIdx = cIdx * 10 + fIdx;
                  const isOpen = openIdx === globalIdx;

                  return (
                    <div
                      key={fIdx}
                      className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-xs"
                    >
                      <button
                        onClick={() => setOpenIdx(isOpen ? -1 : globalIdx)}
                        className="w-full p-4 sm:p-5 text-left flex items-center justify-between font-bold text-xs sm:text-sm text-slate-900"
                      >
                        <span>{faq.q}</span>
                        {isOpen ? (
                          <ChevronUp className="w-4 h-4 text-emerald-600 shrink-0" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-slate-400 shrink-0" />
                        )}
                      </button>
                      {isOpen && (
                        <div className="px-4 pb-4 sm:px-5 sm:pb-5 text-xs text-slate-600 leading-relaxed border-t border-slate-100 pt-3">
                          {faq.a}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
